version: '3.9'
services:
  quarkus:
    build:
      context: .
      dockerfile: Dockerfile.native
    image: backend
    container_name: backend
    ports:
      - 63002:8080
    restart: always
#./mvnw package
#docker-compose up --build -d
