version: '3.9'
services:
  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    image: native/aquaher
    container_name: backend
    ports:
      - 63002:8080
    restart: always
#./mvnw package

