version: '3.9'
services:
  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: production
    container_name: backend
    ports:
      - 63002:8080
#./mvnw package

